### ISSUE TITLE
Fix missing resolver for to_one when the foreign key is in the target model

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#117]
This is a somewhat confusing case, because actually when using foreign keys and assuming a to_one association, the foreign key naturally needs to be in the source data model. Example a Dog has one Owner, the Person-ID would be in the Dog. If an Owner has also just one Dog, that can only be enforced by e.g. a unique constraint on the Person-ID column in the Dog data model. That is why we so far "overlooked" this case. None the less, we want to implement it.

Add the required resolvers and write integration tests.

The code generator should raise a WARNING if this case is found and inform the user that a validation, e.g. a unique constraint needs to be added, to ensure that a Owner truly ends up with just one Dog.

Note this example and what to do if no 'unique' constraint is implemented by the user:

1. Fetch Person
2. Invoke addPerson in Dog
3. Read Dog through `dog(search)` field resolver
4. No foreign key has to be set manually, because 3. only needs to provide the personId:
   -> Raise a benign error, of more than one record is found

Raise a benign error, of more than one record is found.

**Comment by asishallab** [comment]
Template for the benign error message. Consider association `unique_dog` in Person, where the foreign-key `person_id` is stored in the `Dog` data model.

`Not unique to_one association error: Found ${dogs.length} dogs matching your query. Consider using unique constraints or move the foreign key into the Person model. Found Dog ${model.dog.idAttrName}s: [...]`

**Comment by coeit** [comment]
implemented and merged into 
https://github.com/ScienceDb/graphql-server-model-codegen/tree/issue107-refactoring
