### ISSUE TITLE
When administering to_one associations make the consistency checks part of the SQL queries, too

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#118]
When e.g. removing a Person from a Dog's owner, check if the Dog is actually associated with the Owner before you set the Dog's owner to `null`. If you do not do this check, you might "remove" an Owner that is actually not associated with the respective Dog. 

"Repeat" i.e. include this check on the level of the generated SQL statement:

Instead of
`UPDATE dogs SET owner_id NULL WHERE dog_id = ${dogId}` use
`UPDATE dogs SET owner_id NULL WHERE dog_id = ${dogId} AND owner_id = ${ownerId}`

**Comment by coeit** [comment]
implemented and merged into
https://github.com/ScienceDb/graphql-server-model-codegen/tree/issue107-refactoring

commit:
https://github.com/ScienceDb/graphql-server-model-codegen/commit/928ac59685ff1c89d7eebb7f613ccb6aa8461f13
