### ISSUE TITLE
Check authorization, record limit, and validate association arguments in to_any_through_sql_cross_table associations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#121]
Adhering to Cenzontle's standard. The field resolvers, and possibly so called "infix" functions, e.g. `add_person`, must do the following checks and adjustments:

* check authorization
* validate association arguments
* diminish record limits

**Comment by coeit** [comment]
implemented and merged into branch
https://github.com/ScienceDb/graphql-server-model-codegen/tree/issue107-refactoring

commit:
https://github.com/ScienceDb/graphql-server-model-codegen/commit/928ac59685ff1c89d7eebb7f613ccb6aa8461f13
