### ISSUE TITLE
Throw an "No record exists with this ID" if no record can be found for a given ID

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#128]
Especially data model of storage-type `SQL` should throw an error, if there is no persistent record for the input argument `ID` (`<idAttribtue>`).

**Comment by asishallab** [comment]
This check, and possible error generation, should happen in the model layer. For generic models add a remark in the function comment (JSDoc) that such an error _must_ be thrown if no record for the argument ID is found. Thus the programmer knows or is reminded to implement it in that way.

**Comment by vsuaste** [comment]
Done. Commit [#4d47afb](https://github.com/ScienceDb/graphql-server-model-codegen/commit/4d47afb87cdb8f78f620ddf6e218395107eee260)
