### ISSUE TITLE
Generate comprehensible usage guide in the README

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#14]
The `README` is generally the first encounter with a Github project. Here we need to explain, how the code generator is used. So far none of the possible input `JSON` arguments are explained in detail. Please provide documentation on the possible structure and arguments of the input `JSON` files. Pointing to the example directory does _not_ suffice.

**Comment by vsuaste** [comment]
Done. [#f9871e](https://github.com/ScienceDb/graphql-server-model-codegen/commit/f9871e922df0d5e1e9bf304ddcb018748f004bd4#diff-04c6e90faac2675aa89e2176d2eec7d8)
