### ISSUE TITLE
**Add limits to all resolvers**

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#26]
* Maximum limit as an environment variable
* Default 10,000
* If requested number of records would exceed the maximum value generate an error.

**Comment by asishallab** [comment]
If an error is generated use something alike to the following error message template
`Error: Requested ${model.count(options)} exceeding max limit of ${BATCH_MAX_SIZE}. Please use pagination.`

**Comment by asishallab** [comment]
To give an example of possible paginated queries:
```
{ people(pagination: {limit: 10000, offset: 0}) {
     name
     dogs(pagination: {limit: 10000, offset: 0}) { 
        breed
     }
}

**Comment by vsuaste** [comment]
Done. [#e735f0](https://github.com/ScienceDb/express_graphql_model_gen/commit/e735f0bb8b84674b3a9708329948239fe66386d6)
