### ISSUE TITLE
Bulk create should be streamed

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#27]
When uploading CSV or XLSX (Excel) tables to bulk create records, accept files with a maximum file size _only_. This maximum file size should be settable as an environment variable and by default be 500MB.

Apart from this limitation no further limits shall be implemented. To avoid high memory loads or even out-of-memory-crashes use streams both for processing up-loaded tables in bulk-create, as well when generating downloadable tables. 

In order to facilitate this, the GraphQL context must contain the HTTP-response object, which is a stream in express. Add the response to the context and implement the requested features. See [this Issue](https://github.com/ScienceDb/server-graphql-sequelize/issues/1)

**Comment by asishallab** [comment]
Only if this is too difficult to implement in GraphQL, consider adding GraphQL independent routes, that can be mounted within the express server of the skeleton project without being actually GraphQL mutations. 
So we would have the following routes:
* `www.my-science-db.org/graphql` where express-graphql is mounted with the respective schema and resolvers
* `www.my-science-db.org/people/example_csv` to download an example CSV file for the data model "`Person`"
* `www.my-science-db.org/people/upload_csv` to bulk create records from an uploaded CSV file for the data model "`Person`"
* `www.my-science-db.org/people/upload_xlsx` to bulk create records from an uploaded XLSX file for the data model "`Person`"
etc.

**Comment by asishallab** [comment]
Helpful code snippets and packages.

General information on how to use streams in Node.js see [this blog] (https://medium.freecodecamp.org/node-js-streams-everything-you-need-to-know-c9141306be93)

* To convert an uploaded CSV file using streams into objects use: [csv-parse](https://www.npmjs.com/package/csv-parse)
* Write a result stream, if possible with Sequelize, into a downloadable table:
```
while ( batch still to fetch ) {
  let batch = await model.people.findAll(batchOptions)
  csvTableStream.write(batch)
}
``` 
If this is not possible, or no solution is found after three hours of investigation, abandon this task and generate an error, if more than MAX_BATCH_SIZE records would be exported to the downloadable file.

**Comment by asishallab** [comment]
### Modification:  Only implement upload / bulk create for now

**Comment by MichalCz** [comment]
Hi,

You could cheek out my framework: [scramjet](https://www.npmjs.com/package/scramjet). This way you can turn the stream from request into an async generator and use for-await-of to iterate over csv entries.

It may be what you're looking for.

**Comment by asishallab** [comment]
In the near future the implementation for XLSX files will follow. For now, the Issue is considered closed.
