### ISSUE TITLE
Extend table creating migrations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#32]
When code generating a migration that creates a new tables, ensure that primary _and_ foreign key columns are indexed.
Also add on update cascade and on delete cascade, especially in cross-tables.

Helpful reading:
* [Add / alter constraint](https://www.postgresql.org/message-id/AANLkTim0_j4QhMxm0PQ22MuOXR4iPW1zz%3Dt5PYeRUX_1%40mail.gmail.com)
* [Migration QueryInterface functions](http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html)

**Comment by vsuaste** [comment]
Done. Commit [#50bed0](https://github.com/ScienceDb/graphql-server-model-codegen/commit/50bed0919f0cbb1fef1e0f99362ed450d7a957c3)
