### ISSUE TITLE
Use the 'name' of associations as a base for the generated queries and resolvers

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#42]
How to define associations between models is explained in [this document](https://sciencedb.github.io/dataModels.html).

For instance a Dog might have an associated instance of the `Person` model. Note that the data model `Person` is named exactly that: `Person`, as defined by the `"target"` argument below.
```
"associations" : {
    "person" : {
      "target" : "Person",
        // ...
    }
  }
```

Enable naming the association any way the user likes, e.g. `Owner`, but still be linked to the correct data model `Person`. All related queries, mutations, and resolvers should be named respectively.

### Expected work time: 6h

**Comment by vsuaste** [comment]
Done. Commits [329853](https://github.com/ScienceDb/graphql-server-model-codegen/commit/32985346032fee2d658b9d4984c7c5ebf555f1f7) [0791f0](https://github.com/ScienceDb/graphql-server-model-codegen/commit/0791f0ec9341c21d5701c083eb174c4c641481b4) [0c43ca](https://github.com/ScienceDb/graphql-server-model-codegen/commit/0c43ca4e2d41b3dfa82a4e4ec8a9cc1fe343d06f)
