### ISSUE TITLE
Upper case letters in the model name

### ISSUE THREAD

**Issue by YKolokoltsev** [ScienceDb/graphql-server-model-codegen#43]
In the model definition JSON file, the first that is defined the model name. The back-end code generator uses this name to defie the names of the functions of the GraphQL interface and the name of the JSON object “class” that represent a single object stored in the table.

In the case if we use the letters of the upper case in the model name definition, the name of the JSON object used in the GraphQL schemas will be the same (see `docker/integration_test_run/schemas`). However, in the JSON model definition generated (see `docker/integration_test_run/models-webservice`), the model name automatically converts to all downcase letters in the class name. As a result, when GraphQL server is loaded, none of the functions of the model interface will be present.

BUG Repeat:

1. In the file test/integration_test_input/amino_acid_aequence.json change

``
"model" : "aminoacidsequence"
``
to

``
"model" : "aminoAcidSequence"
``

2. Run the integration-test.sh script

As a result,  the test named `02. AminoAcidSequence:  read one` will fail with 400 error.

For the moment this was tested fo the Web service model, therefore the same shell be checked for the case of regular models (actually both the individual and transcription_count have a lower case names).

**Comment by YKolokoltsev** [comment]
New observatios:

As it was mentioned by Veronica, the most probably that the problem is related with GraphQL functins names that do not coincide with the class name of the WebService.

**Comment by vsuaste** [comment]
Done. Commit [#46b4bf](https://github.com/ScienceDb/graphql-server-model-codegen/commit/46b4bfdfc349743c30b993d5f47e59f6111224bd)
Model's name can be upper or lower case, can be also camel case and using underscore.
Note: Names with hyphen won't be allowed because resolver can't be named with hyphens.
