### ISSUE TITLE
Offer the user to specify on which columns to create database indices

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#45]
So far the migrations created for data models stored in relational databases ("`SQL`") get some default indices created alongside, namely indices on foreign keys.

Add an additional _optional_ argument like so:
```
{
  "model" : "dog",
  "storageType" : "SQL",
  "attributes" : {
    "name" : "String",
    "age": "Int"
  },
  "indices": ["name", "age"]
} 
```
The above example would generate a migration that creates two non default indices on the columns "`name`" and "`age`".
_Note_ that this should _not_ replace the creation of indices on foreign key columns. 

Pleas remember to add documentation especially in our manual about which foreign keys are created by default and, of course, about this new optional argument.

### Expected work time: 3h

**Comment by vsuaste** [comment]
Done. Commit [#64ea21](https://github.com/ScienceDb/graphql-server-model-codegen/commit/64ea2147e569d400af4396add7e3c87d38be4d6f)
