### ISSUE TITLE
Extend the existing data model type 'web-service' to have the complete CRUD API

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#48]
The web service data model actually enables the user of Science-DB's code generators to create a module of method stubs. This is, because a web service is not a well defined API for data storage like for instance a relational database in which we can define the schema and have standardized access functions (SQL).

Hence the web service data model is an interface of order to chaos. The order being the well structured schema and API of Science-DB CRUD data models and the chaos the unpredictable non standardized interface which can be for instance a web endpoint.

This already shows us, that the name of this type of Science-DB data model `web-service` is ill chosen, as the generated code does not have any predefined functions to connect to web-servers. `CRUD-stub` or simply `stub` might be a better name for it. After all we could use it to write an interface to chaos being a file based home grown database system.

All this rant to explain why we need to include the full CRUD API support to be implemented in `web-service`. This _must_ include also everything related to associations with other models.

All generated resolvers should be default include code comments like
```
// Please fill in your code here. As this is the `readAll` implementation, 
// your code should provide access to all records of this data model.
```
The latter part of the code comment should briefly describe what the function stub is meant to do.

Also, all generated function stubs should through a `not implemented` error.

Finally, we should also think of renaming this data model type.

### Expected work time: 3h

**Comment by vsuaste** [comment]
Done. Commit [#bf5667](https://github.com/ScienceDb/graphql-server-model-codegen/commit/bf56674a7d9fb71a9cde70527364219ce706534c)

### Actual work time 7hrs 
(refactoring generator thinking also in other storage types)
