### ISSUE TITLE
Add default 'ORDER BY id ASC' to pagination if no other ordering is set

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#51]
Because in relational databases there is no default order of records there is no guarantee that you pagination works without an explicit ordering. 

See [this post on Sequelize](https://github.com/sequelize/sequelize/issues/9289) and specifically [this post](https://stackoverflow.com/questions/6585574/postgres-default-sort-by-id-worldship) on Postgres.

Write a new function, possibly within a `helper` module, which does pre filtering of the three related `find all` arguments `search`, `pagination`, `order`. In case a pagination argument is supplied (`!== undefined`) and _no_ order argument is supplied (`=== undefined`), set a default order argument `ORDER BY id ASC`.

### Expected work time: 3h

**Comment by vsuaste** [comment]
Done. Commit [#d96374](https://github.com/ScienceDb/graphql-server-model-codegen/commit/d96374e7d20963b8cff0c1d1567dbf50116df890)
