### ISSUE TITLE
In ACL use model name and not pluralized lowercase version of it

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#52]
Consider having defined a model named `Book`, then the ACL authorization module needs to say
```
allows: [{
      resources: ['books'],
      permissions: 'read'
    }]
```

It would be better to enable usage of the model name as it was given by the user, i.e.
```
allows: [{
      resources: ['Book'],
      permissions: 'read'
    }]
```

The generated code must be adjusted from:
```
return checkAuthorization(context, '<%- namePl -%>', 'create').then( authorization =>{
```
to
```
return checkAuthorization(context, '<%- name -%>', 'create').then( authorization =>{
```

**Before implementation assess the impact of this Issue.** If too big, discuss with team before making changes.

### Expected work time: 2h

**Comment by vsuaste** [comment]
Done. [#0c9537 ](https://github.com/ScienceDb/graphql-server-model-codegen/commit/0c953750f4146983b97135e12c395e4e0b1e90f3)
