### ISSUE TITLE
Implement 'Sequelize'-independent validation for any data model

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#53]
### Introduction

Validation as implemented in [`Sequelize`'s validation framework](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#validations) is great and serves all our purposes. Sequelize uses the popular [`validator.js`](github.com/guillaumepotier/validator.js) for this. Unfortunately, ScienceDb is going to support many different storage technologies, like Apache's Cassandra, MongoDB, and CSV-Tables stored on Minio through Amazon's AWS S3 SDK. Hence we need a validation method to work independently of Sequelize.

To separate a data model's (DM) validation from the automatically generated model, its resolvers, its schema, and its migrations, we want our validation framework to keep validation rules in a separate space which will not be overwritten should code generators be run again, e.g. in slightly changed model definitions.

Furthermore we want to enable different validations before `create`, `update`, and `delete` events. But by default the same validation should be applied in all three cases. 

**Most importantly** the new validations need to maintain the validation error format currently supported by ScienceDb in order to avoid the need for refactoring. Ask @vsuaste for details on this format.

_Which validation framework to choose?_ Well considering [this statistic](https://www.npmtrends.com/joi-vs-validate.js-vs-validator.js-vs-yup) of weekly downloads of popular NodeJS validation frameworks [`joi`](https://github.com/hapijs/joi) is the clear winner.

### Implementation

The code generators (CG) should create, if not already present, a `validations` directory. And _only, if not already present_ a validation module file called `<my_data_model>_validator.js`, where `<my_data_model>` obviously is the currently processed data model name, e.g. `book`.

Given the above data model example `book` the following module `validations/book_validator.js` should be created, if and only if it does not already exist. The module uses [`joi`](https://github.com/hapijs/joi) to facilitate validations.
```
// book_validator.js

// Make sure something like the following comment appears in the generated module:
// Delete this file, if you do not want or need any validations.

// book has two attributes price and title
// This is Pseudo-Code to explain what is expected as a result if this issue
const Joi = require('joi')
const book = require(path.join(__dirname, '..', 'models', 'book.js'))

// Make sure something like the following comment appears in the generated module:
// Dear user, edit the schema to adjust it to your model
book.prototype.validatorSchema = Joi.object().keys({
    // NOTE that the default validations check for respective attribute type!
    price: Joi.string().alphanum(),
    title: Joi.string()
})

book.prototype.validatForCreate = function(record) { 
  return Joi.validate(record, book.prototype.validatorSchema)
}

book.prototype.validatForUpdate = function(record) { 
  return Joi.validate(record, book.prototype.validatorSchema)
}

book.prototype.validatForDelete = function(record) { 
  return Joi.validate(record, book.prototype.validatorSchema)
}
```

Adjust the `resolvers` generated by this CG to automatically invoke the validation functions defined by above validation module. Write a utility helper that implements the following two steps:
```
// validatorUtil.js
module.exports.ifHasValidatorFunctionInvoke = function( validatorFunction, dataModelInstance ) {
  // checks if the function "validatorFunction" is present in "dataModelInstance"
  // if it is found the validatorFunction is invoked and possible errors returned
}
```

The `resolvers` should then be modified to do as shown in the following example for the `create` case:
```
// book_resolvers.js
const validatorUtil = require('validatorUtil')

function create( args ) {
  let bookRecord = // somehow constructed from args
  let valErrors = validatorUtil.ifHasValidatorFunctionInvoke( 'validateForCreate', bookRecord )  
  // handle errors as before when still using Sequelize's validation framework
}
```

If needed write a utility helper that converts `joi`'s validation errors to the format currently processed in ScienceDb.

_Please remember to_ 
- also write unit and integration tests,
- document all functions according to the JSDoc standards,
- use a separate Git branch for this Issue, 
- be brief and concise when talking to other programmers in order to obtain information on e.g. ScienceDb's error formats, and
- aim to keep within the expected work time, raising an alarm when after having used half the expected time a timely end is no more likely.

#### Hint

It might make the work easier to use a working life example of a ScienceDb installation and develop the needed code within it, before migrating it into the code generator(s). You can use [this implementation of ScienceDb](https://github.com/ScienceDb/ScienceDbStarterPack/tree/BreedPatH).

**Comment by YKolokoltsev** [comment]
All done except for the XLS batch upload validation, because there is no streaming yet.
