### ISSUE TITLE
Implement the new web-service data model type "sciencedb-web-service" that communicates with a remote Science-DB server 

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#55]
### Implement the new web-service data model type "sciencedb-web-service" that communicates with a remote Science-DB server

We already have a data model type called ["web-service"](https://sciencedb.github.io/dataModels.html) that generates code for a remotely stored data model.

Within the resolvers of web-service data models by default an `not implemented` error is generated and the user of Science-DB's code generators is expected to fill in the custom code to enable communication with the remote server. This is necessary because a web-server per se has not a standardized API which enabled our code generators to create the complete already fully working resolvers.

However, if we assume the remote web server to be an instance of Science-DB we already know what the GraphQL schema for a given data model looks like, and thus we can create fully functional resolvers for "sciencedb-web-servers".

So, write code generators for this new data model type "sciencedb-web-service". The JSON input will have an additional attribute `baseUrl` which should be e.g. `www.myScienceDbImpl.org/graphql`.

If the sciencedb-data-model `Book` has the following definition
```
{
 "model" : "Book",
 "storageType" : "SQL",
 "baseUrl": "www.myScienceDb.org/graphql",
 "attributes" : {
        "id" : Int,
        "title": String,
        "ISBN": Int
  }
}
```

The resulting code should include something like the following resolvers
```
readOneBook: function({
        id
    }, context) {
        let graphQlQuery = `{readOneBook(id: ${id}) { id title ISBN }}` 
        return axios.get( this.baseUrl, grahQlQuery ).then( res => { ... } )
    }
```

Please write unit and integration tests and also include relationships.

### Expected work time: 1d

**Comment by asishallab** [comment]
### Expected work time: 1h

**Comment by vsuaste** [comment]
Commits: [#9b7938](https://github.com/ScienceDb/graphql-server-model-codegen/commit/9b7938a4d17ceea2463eb49e3180c103768bceeb) [#e6c390](https://github.com/ScienceDb/graphql-server-model-codegen/commit/e6c390fa427ee093d400620ac6c5c4f6a746861e) [#317519](https://github.com/ScienceDb/graphql-server-model-codegen/commit/31751970da74e65ac1beaffd1ef0980e4da9ff7f) [#7cc91c](https://github.com/ScienceDb/graphql-server-model-codegen/commit/7cc91cfc9338fe97b36b10f2681bfdd89deb3687) [#a04d2e](https://github.com/ScienceDb/graphql-server-model-codegen/commit/a04d2e7905b90b3c0af8fb85e5b594449322cfd5) [#cbd7b0](https://github.com/ScienceDb/graphql-server-model-codegen/commit/cbd7b082dcf3871d195b49e84bbdfbd4682c3eab) [#29c7d7](https://github.com/ScienceDb/graphql-server-model-codegen/commit/29c7d7d0a60893f22145004a9e76b6c709bd81e2) [#a9bedd](https://github.com/ScienceDb/graphql-server-model-codegen/commit/a9bedd1e02b9512304dc59e29faf58b95c42e2a8) [#52605f](https://github.com/ScienceDb/graphql-server-model-codegen/commit/52605f38f2619c3f364303afba9f0c8040ada2ff) [#6d0b61](https://github.com/ScienceDb/graphql-server-model-codegen/commit/6d0b6171301c5ad61ac644be774064bafa0b837d) [#47fd59](https://github.com/ScienceDb/graphql-server-model-codegen/commit/47fd59caf5b46ceb41cb341239427da3ad7b24ba) [#02d9c6](https://github.com/ScienceDb/graphql-server-model-codegen/commit/02d9c63e4cd2221589374bf646dce0295dd40ace)
