### ISSUE TITLE
Environmetal variable for temporary directory

### ISSUE THREAD

**Issue by vsuaste** [ScienceDb/graphql-server-model-codegen#61]
Allow the user to specify the the temporary directoy where the batch upload creates a temporary file.
This implementation goes in the `create_resolvers.ejs` view. Line 305 in this [file](https://github.com/ScienceDb/graphql-server-model-codegen/blob/master/views/create-resolvers.ejs)

**Comment by asishallab** [comment]
Found a very simple solution.

Using `os.tmpdir()` to find and use the system's temporary directory. 
In the production `docker-compose.yml` the container's `/tmp` volume is mounted onto the host system's `/tmp`. 

[commit in `ScienceDbStarterPack`](https://github.com/ScienceDb/ScienceDbStarterPack/commit/d94c67df949a945e5044c075657d8f416d27d622)

[commit in `graphql-server-model-codegen`](https://github.com/ScienceDb/graphql-server-model-codegen/commit/cccaf2f1ea0c556f77d22c6580034ee494c0729d)
