### ISSUE TITLE
Create a general `model` layer interface

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#64]
Currently a data model has its API implemented across three modules:
* a GraphQL schema
* a `data-model` in `models`
* a `resolver` in `resolvers`
* a `validation`

The relationship between the data model module and the resolver module is still too "intimate". The resolver should have standardized functions with standardized arguments, an interface, exposed. Thus, when implementing support for other storage technologies only the model might need re-implementation and the resolvers can be created as they already are.

For a basis of the definition of this interface see [this defining document](https://docs.google.com/document/d/113Lj0BvlZ2Wu-_cZWfiizYhLgN-z1lC56Tpy17oCB6k/edit?usp=sharing)

### Expected work time: 3 to 5 days

**Comment by vsuaste** [comment]
Steps done:

* Sequelize models have been extended to a class. [#2d04f1](https://github.com/ScienceDb/graphql-server-model-codegen/commit/2d04f1002c6a694edcf888c71a5ae92bfeb7dac0)
* Base64 enconde and decode methods have been added as part of the model layer [#31138c](https://github.com/ScienceDb/graphql-server-model-codegen/commit/31138cc7522f0f3b19bd92b3d6056029dad32a33).
```
base64Enconde()  //member function
static base64Decode( cursor ) //class level function
```

**Comment by asishallab** [comment]
### New / additional functions

Some important new functions that are required for validation have been added to the "`Interface`" which we implement here. See chapter "validation functions" in [our defining document](https://docs.google.com/document/d/113Lj0BvlZ2Wu-_cZWfiizYhLgN-z1lC56Tpy17oCB6k/edit?usp=sharing) for details.

**Comment by asishallab** [comment]
### Assume asynchronous validation

In the three cases, we do validation by default `create`, `delete`, and `update`, please consider now an asynchronous validator. For details please see the [modified `validatorUtil.js`](https://github.com/ScienceDb/graphql-server/blob/async-validation/utils/validatorUtil.js).

Do something like this:
```
let valResult = await validatorUtil.ifHasValidatorFunctionInvoke('validateForCreate', <%- nameLc -%>, input)
```
or use the classic `then(...).catch(...)` construct.
```

**Comment by asishallab** [comment]
### Unify the resolver layer

Because the Model Layer will have a well defined API (Interface) we can take advantage of this and provide a unified Resolver API (Interface) independent of the storage technology implemented in the various data models.

Following from this we will remove any storage technology dependent resolvers, like e.g. the Sequelize specific `belongsToMany` which is a many-to-many association. We will offer a `many-to-many` association type, which will just be a shortcut for a cross-model.

The user needs to define the respective cross-model and also the respective `one-to-many` associations to enable the usage of the shortcut `many-to-many`. Consider the following example:

An Author may have written many Books, and Books may have many Authors.
The respective GraphQL queries would look like this:

```author(id: 1) {
   author2Books() {
      books() {
         title
      }
   }
}

author(id: 1) {
   books() {
     title
   }
}

// Resolver:
Author.books = function(...) {
    this().author2books().books()
}

// classic oneToMany
Author.author2books```

Comment for the documentation:

If you define a manyToMany association, you ALSO need the oneToMany to the cross model in your associations. The manToMany will then just be implemented as a shortcut

**Comment by asishallab** [comment]
### The problem with Many-To-Many Associations

Writing a general many-to-many association resolver is _not_ trivial. Two problems arise. Firstly our current abstraction has no filter function for the any to-one associations. Thus short cutting the cross model looses the option to filter the records of the target data model. Secondly we can cause performance issues when implementing as a GraphQL resolver what is a `table join` in relational databases. We would need to do this supporting pagination. For more details on these two problems see [the minutes](https://docs.google.com/document/d/1LUzDGiAx8igE2vs0UKI2_1aMdSPWWUKim9Jg5orcWTo/edit?usp=sharing) of a web conference of the authors.

To keep this Issue still in check, we will implement the "selected solution" as presented in the above minutes. In summary two things have to be done:

- Add a search argument to has-one associations. If the associated record matches the provided search argument it is returned, otherwise `null` is returned.
- The default implementation in the data model of has-many associations is throwing an `not implemented` error. If both data models reside in storage type `SQL` the current Sequelize specific `join` cross table based solution is used. 
  - Switch the conversion of GraphQL schema based search, pagination, and sort arguments into the data model layer. 
  - Call the corresponding data model layer functions `*Impl`.

**Comment by asishallab** [comment]
Issue #66 is part of this refactoring introducing more abstraction between Resolvers and Data Model Layers.

**Comment by vsuaste** [comment]
Done. Commits [](https://github.com/ScienceDb/graphql-server-model-codegen/commit/31138cc7522f0f3b19bd92b3d6056029dad32a33) [#9f7586](https://github.com/ScienceDb/graphql-server-model-codegen/commit/9f75866e86dd9484127d55ba3549ab1b512cbd48) [#a701c8](https://github.com/ScienceDb/graphql-server-model-codegen/commit/a701c872ef9522ecf24b7ce508ae0a2acb24e866) [#6d1656](https://github.com/ScienceDb/graphql-server-model-codegen/commit/6d1656a13d967211e9afefaa9d9b646276ce42b2) [#ebd242](https://github.com/ScienceDb/graphql-server-model-codegen/commit/ebd2421fa5b2a4078396908542143e8b868eb660) [#0b2e1c](https://github.com/ScienceDb/graphql-server-model-codegen/commit/0b2e1c980ac7012c5f304b2398281f9920f44478) [#aeb6e2](https://github.com/ScienceDb/graphql-server-model-codegen/commit/aeb6e24e0cc328ca09fee949ab4876f5f8e4be82) [#6bc4e4](https://github.com/ScienceDb/graphql-server-model-codegen/commit/6bc4e4eb0e3b4d3d763226297eddbb6ae6575881) [#c59979](https://github.com/ScienceDb/graphql-server-model-codegen/commit/c59979c65f4c667a2811670be113dfbb318349a1)
