### ISSUE TITLE
Decouple hasOne/belongsTo and hasMany association resolvers from their implementation

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#66]
Consider how we solved the part of resolvers of many-to-many associations in Issue #64 .

Implement the same delegation of the GraphQL resolver to the data model layer. This means for hasMany associations the resolver should look something like the following example. Consider Dog has-many Fleas:

```// Resolver in Dog
Dog.fleaFilter( {search, pagination, order}, context ) {
   return dogDataModel.fleaFilterImpl( {search, pagination, order} )
}

// Dog Data Model
fleaFilterImpl( {search, pagination, order} ) {
   // default implementation is to use our resolvers:
   let extSearch = search.merge( /* where dogId = this.id */ )
   return Flea.readAll( { extSearch, pagination, order } )
}
```

The same must be done for hasOne or belongsTo associations. Considering the above Dog and Flea example the inverse association would look like this:

```// Resolver in Flea
Flea.dog({ search }, context) {
   return fleaDataModel.dogImpl( {search} )
}

// Flea Data Model
dogImpl( {search} ) {
   // current default implementation
   return Dog.readOne( this.dogId )
}
```

**Comment by vsuaste** [comment]
Done. [](https://github.com/ScienceDb/graphql-server-model-codegen/commit/124b8a575e3110577b6cace895659469dcc19aa2) [#81766c](https://github.com/ScienceDb/graphql-server-model-codegen/commit/81766c3337b8fb12ed7cefcda62edab748eec62e) [#d6e78f](https://github.com/ScienceDb/graphql-server-model-codegen/commit/d6e78fb0d9f634cba54b0c948a53b5f52e2b15c3) [#19b994](https://github.com/ScienceDb/graphql-server-model-codegen/commit/19b994943ad5cd85a84a9fa6367cc89f2c1bbbd8) [#22b87f](https://github.com/ScienceDb/graphql-server-model-codegen/commit/22b87f5898cd21c8c731816dca34a295cd1e8d02)
