### ISSUE TITLE
Make integration test suite more agile - change command line arguments

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#67]
### Introduction

See [this white paper](https://docs.google.com/document/d/1twnXUrdi8G-mXzNycdnAlx0ZvGNxcd9rMVsofnSEt4M/edit?usp=sharing) on the motivation and design changes planned for the integration-test-suite.

### Details

Keep in mind, that the integration-tests are carried out by different scripts and files. They can be identified by following down the invocation chain from `"test-integration": "bash ./test/sh_integration_test_run.sh"` (package.json).

Adjust the integration-test-suite (ITS) to the following default behavior.
* By default do the cleanup at the very beginning and the very end. Cleanup involves deleting the generated code, invoking `down` on the respective docker-compose, and deleting the respective Docker images.
* The generated code shall as before be kept in the folder `./docker/integration_test_run/`, Adjust the Docker-files to no longer copy the code into the respective images, but use mounts to make the code available inside the Docker containers.
* Add the option `--keep-running` which skips the cleanup step at the end of the test-suite and keeps the Docker containers running.

Add new commands that deviate from the default behavior.

1. `--restart-containers`: This command stops the running containers via `docker-compose down` and restarts them. Because the containers managing the test-suite's databases do not use docker named volumes, but transient ones, the databases will be re-initialized by this command, too.
2. `--generate-code`: This option automatically starts by executing command 1. `--restart-containers`. Empty directory `./docker/integration_test_run/`. Then, use the project's current base (as in your local copy of the code-generator-repository) to generate the code for the test models.   
3. `--run-tests-only`: This option automatically starts by executing command 1. `--restart-containers`. Subsequently, execute the integration tests.
4. `--generate-code-and-run-tests`: Combines the commands 1., 2., and 3. in that order.
5. `--cleanup`: Executes the cleanup step as explained above in the default behavior. 

Hint on how to delete and re-create the database:
You can use the node script [`testSequelizeDbServerAvailable.js`](https://github.com/ScienceDb/graphql-server/blob/master/utils/testSequelizeDbServerAvailable.js) as a template to implement the deletion and re-creation of the database used by the integration-test-suite. Make sure that the database is only deleted if it exists, and only created if it does not. See [this post on Stackoverflow](https://stackoverflow.com/questions/31294562/sequelize-create-database) and the [Sequelize documentation](https://sequelize.org/master/manual/raw-queries.html) on how to execute SQL commands via Sequelize.

Note, that the `npm install --save` command in the `Dockerfile.graphql_server` will be no longer needed, but needs to be executed on startup of the graphql-server Docker container in the respective docker-compose-test.yml (see [this docker-compose](https://github.com/ScienceDb/ScienceDbStarterPack/blob/master/docker-compose-dev.yml) for details): 
```
command:
      - /bin/sh
      - -c
      - |
        npm install
        ./migrateDbAndStartServer.sh
```
Also note, that the respective COPY commands will also no longer be needed in the `Dockerfile.graphql_server`.

Remove the existing command line arguments:
* `--run-docker-only` which just creates the Docker images and starts the docker-compose, but does _not_ execute the test-suite, and 
* `-k <docker-image-name>` which enables to save certain Docker images from being deleted by the cleanup process.

**Comment by asishallab** [comment]
Please make sure that the documentation is updated. Documentation should be in the `bash` scripts in the form of a usage information printed out, in our Wiki, and in the respective Readme file of the code-generator repository

**Comment by framirez07** [comment]
Hi!
The specified functionality is already implemented on branch i67. Documentation was already added to bash script in manpage style (-h option). 

Following are examples of use.

If there are no comments. I would appreciate your approval to proceed to do merge of the brach 'i67' and to close this issue.

Thanks!

EXAMPLES:
    To see full test-integration info:
    $ npm run test-integration -- -h

    To run default behavior (cleanup-genCode-doTests-cleanup):
    $ npm run test-integration

    To run default behavior but skip final cleanup (cleanup-genCode-doTests):
    $ npm run test-integration -- -k

    To restart containers:
    $ npm run test-integration -- -r

    To generate code and start containers:
    $ npm run test-integration -- -g

    To do the tests only and keep the containers running at end:
    $ npm run test-integration -- -t -k

    To generate code and do the tests, removing all Docker images at end:
    $ npm run test-integration -- -T

    To do a full clean up (removes containers, images and code):
    $ npm run test-integration -- -c

![i67_1](https://user-images.githubusercontent.com/53924990/64044957-bad50400-cb2d-11e9-861d-15ca92a58acc.png)
![i67_2](https://user-images.githubusercontent.com/53924990/64044958-bad50400-cb2d-11e9-9eb6-386091ed097a.png)
![i67_3](https://user-images.githubusercontent.com/53924990/64044961-bad50400-cb2d-11e9-9c8c-182ffc9d82c4.png)
![i67_4](https://user-images.githubusercontent.com/53924990/64044962-bad50400-cb2d-11e9-81c0-ed18c080ab68.png)
![i67_5](https://user-images.githubusercontent.com/53924990/64044964-bb6d9a80-cb2d-11e9-83e5-f422008b426e.png)
![i67_6](https://user-images.githubusercontent.com/53924990/64044965-bb6d9a80-cb2d-11e9-8c64-2ec7ac13839f.png)
![i67_7](https://user-images.githubusercontent.com/53924990/64044966-bb6d9a80-cb2d-11e9-89dc-5c6cb3a1cf26.png)
