### ISSUE TITLE
Storage independent resolver - Read Access

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#7]
Consider this an abstract implementation of a GraphQL type (data model) that serves as a code stub  produced by our code generator. It would *require* a programmers attention to fill out the stub functions.

Given the arguments for a model, its attributes, and associations the generator should be able to create the following **resolver** stub functions:

```
async function readOneById(id) {
  // fill in code to obtain a single instance by its ID
}

async function readAll(searchArg, paginateArg, sortArg) {
  // fill in code to obtain either ALL or instances MATCHING the above 
  // search and/or pagination in the stated ordered by sortArg
}

// ASSOCIATIONS
// hasOne "oneModelRel"
async function oneModelRel() {
  return await oneModelRel.readOneById( this.oneModelId )
}

// hasMany "manyModelRel"
async function manyModelRel(searchArg, paginationArg, sortArg) {
  // Here we need to know where the sourceId and targetId are stored (see generator arguments).
  // assume:
  // sourceId: "source_model_id"
  // sourceIdIn: "manyModel"
  return await manyModel.readAll( { field: "source_model_id", operator: "identical", value: this.id } )
}
````

**Conclusion**: The central message of the above is to show, that using our default API with the standard read functions and standard search arguments we are able to implement hasOne and hasMany associations **without knowledge** about the respective data store, be it a relational database, a web service or anything else.

**Comment by asishallab** [comment]
@vsuaste What is the state of this Issue?

**Comment by vsuaste** [comment]
It's done.
The resolvers for webservice storage are created so the user can fill them properly.
And the resolvers for associations (hasOne, hasMany) will use resolvers of target model when
necessary.
