### ISSUE TITLE
Extend the models to accept `add` and `remove` arguments for `to_one` associations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#72]
In consistency with how in the model layer `to_many` associations are implemented, enable the create and update functions to accept `add` and `remove` arguments for each `to_one` association declared in the respective schema. 

Make sure the new arguments work for _all_ implementation types of `to_one` associations, i.e. the `belongsTo` and `hasOne` Sequelize based implementations. Hence, in case of the `hasOne` the respective associated model must be updated as the `foreign-key` is stored there.

Obviously, the `remove` argument does not need to carry a value. Regard the following schema for the data model `Person` that has a single `Betrothed`:

```
addPerson( name: String, addBetrothed: ID!, removeBetrothed: ID ): Person!
```
_Note_ the omitted `!` after `removeBetrothed: ID`.

Please also write unit and a very simple and short integration test.

### Expected work time: 4h

**Comment by vsuaste** [comment]
to-add and to-remove functionalities in ono-to-one associations have been added.
Commits: [#1802e3](https://github.com/ScienceDb/graphql-server-model-codegen/commit/1802e37cece6675f24484eaf2f87313c04147bbb) [#3080fd](https://github.com/ScienceDb/graphql-server-model-codegen/commit/3080fd35e0dd8a7fefff23ef0bf659ac2bc6a76b) [#8dacb8](https://github.com/ScienceDb/graphql-server-model-codegen/commit/8dacb85928a127a3aaecd4fbafb17291d76b6dfd) [#69c7fa](https://github.com/ScienceDb/graphql-server-model-codegen/commit/69c7fa9dc6ab9b8468cfd5ddc0dd9d71e5bf4d16)
