### ISSUE TITLE
AJV should accept NULL values.

### ISSUE THREAD

**Issue by framirez07** [ScienceDb/graphql-server-model-codegen#79]
Actually, **when a NULL value is sent** as a value of some property in a Create or Update operation, **an error "validation failed" is received from Grahpql server**, which in turn is generated by AJV module because null value is not included as a valid value on validation file properties.

By example, the following lines show how the array of types is currently specified (the array of types does not include the null type).
```
"properties" : {
    "variable" : { "type" : ["string"] }
}
```
Thus, when the property, called **_variable_** in this case, is sent to graphql server with a value other than a string, by example: a null value, then the AJV module will throw an error.

To avoid this behavior, according to [official documentation](https://ajv.js.org/keywords.html#type), the NULL type should be included in the array of types. By example:

```
"properties" : {
    "variable" : { "type" : ["string", "null"] }
}
```
**The following image shows an example of the behavior once the 'null' type is included on the array of types.**

![image](https://user-images.githubusercontent.com/53924990/72381253-b8d6a080-36dc-11ea-9430-31a6bff6c478.png)

**Comment by asishallab** [comment]
Please look for a solution and communicate your strategy with the group _before_ implementing it.

**Comment by asishallab** [comment]
Have a look at [this Stackoverflow post](https://stackoverflow.com/questions/45750264/how-add-keyword-nullable-or-allownull-into-ajv)

**Comment by framirez07** [comment]
Hi team!
Following guidelines form Stackoverflow post and Ajv documentation, to accept properties like **null** values like this:
```
{
  variable: null
}
```
An acceptable solution would be do the following additions on file `graphql-server-model-codegen/`**`funks.js`**, on the function where the schema props are defined:

(I left commented current code as '//before')

```
attributesToJsonSchemaProperties = function(attributes) {
  let jsonSchemaProps = Object.assign({}, attributes)

  for (key in jsonSchemaProps) {
    if (jsonSchemaProps[key] === "String") {
      jsonSchemaProps[key] = {
        //before: "type": "string"
        "type": ["string", "null"]
      }
    } else if (jsonSchemaProps[key] === "Int") {
      jsonSchemaProps[key] = {
        //before: "type": "integer"
        "type": ["integer", "null"]
      }
    } else if (jsonSchemaProps[key] === "Float") {
      jsonSchemaProps[key] = {
        //before: "type": "number"
        "type": ["number", "null"]
      }
    } else if (jsonSchemaProps[key] === "Boolean") {
      jsonSchemaProps[key] = {
        //before: "type": "boolean"
        "type": ["boolean", "null"]
      }
    } else if (jsonSchemaProps[key] === "Date") {
      jsonSchemaProps[key] = {
        //before: "isoDate": true 
	      "anyOf": [
          { "isoDate": true },
          { "type": "null" }
        ]
      }
    } else if (jsonSchemaProps[key] === "Time") {
      jsonSchemaProps[key] = {
        //before: "isoTime": true
	      "anyOf": [
          { "isoTime": true },
          { "type": "null" }
        ]
      }
    } else if (jsonSchemaProps[key] === "DateTime") {
      jsonSchemaProps[key] = {
        //before: "isoDateTime": true
        "anyOf": [
          { "isoDateTime": true },
          { "type": "null" }
        ]
      }
    } else {
      throw new Error(`Unsupported attribute type: ${jsonSchemaProps[key]}`);
    }
  }

  return jsonSchemaProps
};
```

Please notice that in `Date`, `Time` and `DateTime` types, the option  **"anyOf"**  is used to add the type 'null'.

Please let me know what do you think about this solution.
Best regards!

**Comment by framirez07** [comment]
Sorry, I'll closed this before by mistake.

**Comment by asishallab** [comment]
That would be the _perfect_ solution. Please implement it as you suggested. Thank you

**Comment by framirez07** [comment]
Implemented on [this commit](https://github.com/ScienceDb/graphql-server-model-codegen/commit/1f9634e7d59a6a669336e44397a8756a8db8bdc1).
