### ISSUE TITLE
Supporting associations - storage independent

### ISSUE THREAD

**Issue by vsuaste** [ScienceDb/graphql-server-model-codegen#8]
# Objective
In order to delimit the topic we will assume that our objetive ~~for now~~  is:

**Allow to a user to manipulate and relate certain number of databases, this includes CRUD operations to the databases and associations among them. The databases can happen to be stored in differente storage type.**  

Assumptions:
1. Storage types supported by now are :
    -  SQL
    -  Web Service
2. Operations supported for WebService databases are only of the read type.

In order to acomplish our objective we separate the work in two main task:
1. Backend code generator (GraphQL)
2. Graphic user interface

*(Within this document we will only discuss the first one)*

## Code generator (GraphQL)
Given a set of data models, the code generator is intended to generate all the code that will be part of the backend. 
#### Input
The **input** for the code generator will be a set of models stored in a folder, each model in a json file. 

*Example:* Let's say we have two data models:` Person` and `Dog` , then we will describe each model in a different file following the specifications in section ??. These files will be saved in the same folder and pass that folder as input for the code generator. In this example the folder was named *DataModels*.
``` 
DataModels 
    |_  person.json
    |_  dog.json
```
## Output
The output is for each model and will be dependant on its storage type. 
1. **SQL**,  support for SQL databases will use sequelize. And the output will be as follow: 
- *schemas* - folder with GraphQL schemas
- *models* - folder with sequelize models
- *resolvers* - folder with resolvers for CRUD operations 
- *migrations* - folder with migrations to update de database(if necessary)

2. **WebService**, output for supporting WebService databases is intended to be completed manually by the user. This output is described as follow:
- *schemas* - folder with GraphQL schemas
- *resolvers* - folder with resolvers' skeleton for Read operations (should be filled by user).

## Data model specifications

Each data model should be described in the json format, one file per model.
The fields that are mandatory to describe each model are the following:

Name | Type | Description
-------- | -------- | --------
 *model* | String | name of the model
 *store* | String | name of the table or document, etc where the model is stored
 *storeType* | String |  one of SQL or WebService
 *attributes* |  Object | Each attribute of the model with its respective type (String, Int, Boolean, Float)
 *associations* (optional) | Object | For description see Section ??

*Example:*
```
// dog.json
{
  "model" : "Dog",
  "store": "dogs",
  "storeType": "SQL",
  "attributes" : {
    "name" : "String",
    "breed" : "String"
  }
}
```

## (Thinking) Associations
For this issue we find two main cases to analyze 
1. Associations contained in their own target/source model
2. Associations that need join model. (manyToMany in SQL, maybe some other...)

The proposed structure for *associations* contains the following fields:

Name | Type | Description
-------- | ------ | -----------
*many* | Boolean | Indicates if an instance of the source model can be associated with many instances of the target model or not. 
*target* | String | Name of the target model of the association
*targetId* | String | Name of the field that will hold the association
*targetIdIn* | String | Name of the model where the targeId will be stored
*targetReference* | String | Name of the model which the targetId refers to
*targetReferenceId* | String | Name of the field which the targetId refers to

*NOTE: We won't need to repeat **store** and **storeType** fields as all this information will be stored for each model description.* 

This structure for associations seems to work for associations of the first case (associations contained in their own source/target model).

**EXAMPLES**
```
// person.json
{
  "model" : "Person",
  "store": "people",
  "storeType": "SQL",
  "attributes" : {
    "firstName" : "String",
    "lastName" : "String",
    "email" : "String"
  },
  "associations" : {
    // Person hasMany Dogs association
    "dogs": {
       "many": true,
       "target": "Dog",
       "targetId": "person_id",
       "targetIdIn": "Dog",
       "targetReference" : "Person",
       "targetReferenceId" : "Id"
    }
  }
}

```
```
// dog.json
{
  "model" : "Dog",
  "store": "dogs",
  "storeType": "SQL",
  "attributes" : {
    "name" : "String",
    "breed" : "String"
  },
  "associations" : {
    // Dog belongsTo Person association
    "owner": {
       "many": false,
       "target": "Person",
       "targetId": "person_id",
       "targetIdIn": "Dog",
       "targetReference" : "Person",
       "targetReferenceId" : "Id"
    }
  }
}
```

What about associations requiring a cross model (join table?) ?
- Cross model needs to be described in its own way.
- Once we have the cross model description, the previous association structure will work for
this type of assciations.

Structure for describing cross models (they can have more than two attributes or fields):

Name | Type | Description
-------- | ------ | ---------------
*model* | String | Name of the cross model
*store* | String | name of the table or document, etc where the model is stored
*storeType* | String |  one of SQL or WebService
*attributes*  | [Object] | Each object contains an attribute of the cross model with its respective information about the models they are refering to.

Each *attribute* object has the next structure:

Name | Type | Description
-------- | ------ | ---------------
label | String | Indicating the field name.
referenceModel | String | Indicating the model which the label refers to.
referenceModelId | String | Indicating the field which the label refers to.

EXAMPLE
```
// person_to_book.json
{
    "model": "person_to_book",
    "store": "people_books",
    "storeType": "SQL",
    "attributes": [
            {
                 "label": "book_isbn",
                 "referenceModel": "Book",
                 "referenceModelId": "isbn"
             },
              {
                 "label": "author_id",
                 "referenceModel": "Person",
                 "referenceModelId": "id",
             }
     ]
}
```
Having this cross model described, we can use it for describing ManyToMany associations, for example, in the `Person` model we will describe the association `Person belongsToMany Book`:

```
//person.json
{
    ...
    associations: {
         ...
       "books" : {
               "many": true,
               "target": "Book",
               "targetId": "book_isbn",
               "targetIdIn": "person_to_book",
               "targetReference" : "Book",
               "targetReferenceId" : "isbn"
         }
    }
}
```
NOTE: We won't need the information about  `Person` model because we can find it in the description of the model `person_to_book`.

## Implementation of code generator for the specific issue of associations

We have to consider three cases:
1. **SQL - SQL** : When both models involved in the association are stored in SQL type.
2. **SQL - WebService** : When one of the models involved in the association is stored in SQL and the one is stored in a WebService.
3. **WebService - WebService** : When both models involved in the association are stored in a WebService.

## RESEARCH FOR ASSOCIATIONS' BEHAVIOR IN OTHER STORAGE TYPES
- *MongoDB*
    - Embedded documents
    - References (almos similar to references in SQL)
    In this case the structure we have for associations will work.
- *HDF5*
- *REDIS*
...

**Comment by asishallab** [comment]
Cross Associations are now possible. See Manual (Wiki) and README
